# Install the apt prerequisites
# addons:
#   apt:
#     packages:
#       - python-pygments

# needed for pygments install
sudo: required

language: python
  
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive  

# Clean and don't fail
install:
  - sudo pip install pygments
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm -rf public || exit 0

# Build the website
script:
  - pygmentize -V
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
