baseURL = "https://jsonhilder.github.io/"
languageCode = "en-us"
title = "Jason's Tech Blog"
paginate = 4

#Notes for usage, to keep a minimal look there are no banners on post pages, but we can add images within the md blog,
#best size or at least how the css has been designed is for ? x ?

[params]
    profilePic = "imgs/profile.png" # for theme version
    
    #blogger Details
    author = "Jason Hilder"
    authorAvatar = "imgs/author_sig.png"
    authorLocation = "Durban, RSA"
    authorWebsite = "https://my-web-site.com"
    Description = "Personal Blog Site"

    #social handles
    twitterName = "JSONhilder"
    fbName = ""
    githubName = "JSONhilder"
    instaName = "jase_hilder"

    #about page
    coverImage = "imgs/about_b.jpg" #ideal banner image size 1920 x 1080 pixels


[menu]
  [[menu.mainmenu]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.mainmenu]]
  identifier = "about me"
  name = "About Me"
  url = "/about"
  weight = 2

  [[menu.mainmenu]]
  identifier = "blog"
  name = "All Blogs"
  url = "/blog"
  weight = 3

  [taxonomies]
  tag = "tags"